CREATE TABLE users (
    id INTEGER(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL, 
    email VARCHAR(50) UNIQUE KEY NOT NULL,
    password VARCHAR(158) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id INTEGER(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL, 
    user INTEGER(11) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);